import makeDebug from 'debug'
import { CLI_NAME } from './constants.js'

const debug = makeDebug(`${CLI_NAME}:comments`)

export const subworkflowMapper = ({ id, filepath }, i) => {
  return `# ${i + 1}. ${id} (${filepath})`
}

export const header = ({ subworkflows }) => {
  debug(`render header`)
  const ts = Date.now()
  let lines = [
    `# Do NOT edit this file directly!`,
    `# Workflow generated automatically at timestamp ${ts} (ms since Unix epoch)`
  ]

  if (subworkflows.length > 0) {
    lines = [
      ...lines,
      `# Subworkflows included:`,
      ...subworkflows.map(subworkflowMapper)
    ]
  }

  return `${lines.join('\n')}\n`
}

export const footer = ({ subworkflows }) => {
  debug(`render footer`)
  let lines = []

  if (subworkflows.length > 0) {
    lines = [
      ...lines,
      `# Subworkflows included:`,
      ...subworkflows.map(subworkflowMapper)
    ]
  }

  return `\n${lines.join('\n')}`
}
